## Preprocessing

In [14]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [15]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.

application_clean=application_df.drop(columns="NAME")
application_clean2=application_clean.drop(columns="EIN")
application_df_clean = pd.DataFrame(application_clean2)
application_df_clean.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [16]:
# Determine the number of unique values in each column.
application_df_clean.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [17]:
# Look at APPLICATION_TYPE value counts for binning
application_df_clean.value_counts("APPLICATION_TYPE")

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T14        3
T25        3
T29        2
T15        2
T17        1
dtype: int64

In [18]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ["T13","T12","T2","T14","T25","T29","T15","T17"]

# Replace in dataframe
for app in application_types_to_replace:
    application_df_clean['APPLICATION_TYPE'] = application_df_clean['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df_clean['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: APPLICATION_TYPE, dtype: int64

In [19]:
# Look at CLASSIFICATION value counts for binning
classification_count = application_df_clean.value_counts("CLASSIFICATION")
classification_count

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C2190        1
C2380        1
C2500        1
C2561        1
C8210        1
Length: 71, dtype: int64

In [20]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts = application_df_clean.value_counts("CLASSIFICATION")
classification_counts_greater1 = classification_counts[classification_counts > 1]
classification_counts_greater1

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C2300       32
C7200       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1278       10
C1238       10
C1235        9
C1237        9
C7210        7
C1720        6
C4100        6
C2400        6
C1600        5
C1257        5
C2710        3
C1260        3
C0           3
C1267        2
C1246        2
C1256        2
C3200        2
C1234        2
dtype: int64

In [21]:
# Classic=fications less than 10
classification_counts = application_df_clean.value_counts("CLASSIFICATION")
classification_counts_lessthan10 = classification_counts[classification_counts < 10]
classification_counts_lessthan10

CLASSIFICATION
C1235    9
C1237    9
C7210    7
C1720    6
C4100    6
C2400    6
C1600    5
C1257    5
C2710    3
C1260    3
C0       3
C1267    2
C1246    2
C1256    2
C3200    2
C1234    2
C4500    1
C4120    1
C5200    1
C3700    1
C6100    1
C4200    1
C1900    1
C2600    1
C1728    1
C1236    1
C1245    1
C1248    1
C1283    1
C1370    1
C1570    1
C1580    1
C1732    1
C2570    1
C1820    1
C2150    1
C2170    1
C2190    1
C2380    1
C2500    1
C2561    1
C8210    1
dtype: int64

In [22]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#classifications_to_replace = ["C1000","C2000","C1200","C1235","C1237","C7210","C1720","C4100","C2400","C1600","C1257","C2710","C1260","C0","C1267","C1246","C1256","C3200","C1234","C4500","C4120","C5200","C3700","C6100","C4200","C1900","C2600","C1728","C1236","C1245","C1248","C1283","C1370","C1570","C1580","C1732","C2570","C1820","C2150","C2170","C2190","C2380","C2500","C2561","C8210"]
classifications_to_replace = classification_count[classification_count <10].index
# Replace in dataframe
for cls in classifications_to_replace:
    application_df_clean['CLASSIFICATION'] = application_df_clean['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df_clean['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Other       98
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
Name: CLASSIFICATION, dtype: int64

In [23]:
# Convert categorical data to numeric with `pd.get_dummies`
#dummy_columns = ["APPLICATION_TYPE","CLASSIFICATION","AFFILIATION","USE_CASE","ORGANIZATION","STATUS","INCOME_AMT","SPECIAL_CONSIDERATIONS","IS_SUCCESSFUL"]
application_df_dummies = pd.get_dummies(application_df_clean)
application_df_dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [24]:
# Split our preprocessed data into our features and target arrays
y = application_df_dummies["IS_SUCCESSFUL"]
X = application_df_dummies.drop(columns="IS_SUCCESSFUL")
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [25]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [28]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = len(X_train_scaled[0])

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=70, activation='relu', input_dim=input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=32, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 70)                4830

 dense_1 (Dense)             (None, 32)                2272

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 7135 (27.87 KB)
Trainable params: 7135 (27.87 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [29]:
# Compile the model
nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [30]:
# Train the model
nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5702 - accuracy: 0.7207
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5535 - accuracy: 0.7303
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5491 - accuracy: 0.7329
Epoch 4/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5471 - accuracy: 0.7329
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5458 - accuracy: 0.7323
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7339
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5439 - accuracy: 0.7347
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7345
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7350
Epoch 10/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5420 - accuracy: 0.7352
Epoch 11/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5409 - accuracy: 0.7360
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7368
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7370
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7364
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7367
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7370
Epoch 17/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5379 - accuracy: 0.7367
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7365
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7383
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7387
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7386
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7385
Epoch 23/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5357 - accuracy: 0.7369
Epoch 24/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5357 - accuracy: 0.7388
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7376
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7395
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7390
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7388
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5342 - accuracy: 0.7388
Epoch 30/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5340 - accuracy: 0.7397
Epoch 31/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5336 - accuracy: 0.7397
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7399
Epoch 33/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5334 - accuracy: 0.7407
Epoch 34/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5332 - accuracy: 0.7399
Epoch 35/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5329 - accuracy: 0.7399
Epoch 36/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5330 - accuracy: 0.7402
Epoch 37/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5327 - accuracy: 0.7399
Epoch 38/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5319 - accuracy: 0.7408
Epoch 39/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5323 - accuracy: 0.7406
Epoch 40/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5319 - accuracy: 0.7414
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5319 - accuracy: 0.7403
Epoch 42/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5316 - accuracy: 0.7412
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5314 - accuracy: 0.7408
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5315 - accuracy: 0.7413
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5313 - accuracy: 0.7407
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5312 - accuracy: 0.7407
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5311 - accuracy: 0.7406
Epoch 48/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5306 - accuracy: 0.7406
Epoch 49/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5305 - accuracy: 0.7403
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5312 - accuracy: 0.7411
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5308 - accuracy: 0.7414
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5306 - accuracy: 0.7410
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5303 - accuracy: 0.7409
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5302 - accuracy: 0.7420
Epoch 55/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5303 - accuracy: 0.7415
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7415
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5302 - accuracy: 0.7423
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5295 - accuracy: 0.7405
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5299 - accuracy: 0.7405
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5296 - accuracy: 0.7423
Epoch 61/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5293 - accuracy: 0.7429
Epoch 62/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5295 - accuracy: 0.7425
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7418
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5292 - accuracy: 0.7411
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5291 - accuracy: 0.7411
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5292 - accuracy: 0.7425
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5292 - accuracy: 0.7426
Epoch 68/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5293 - accuracy: 0.7421
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5290 - accuracy: 0.7415
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5287 - accuracy: 0.7410
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5291 - accuracy: 0.7425
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5285 - accuracy: 0.7423
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5290 - accuracy: 0.7423
Epoch 74/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5281 - accuracy: 0.7420
Epoch 75/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5291 - accuracy: 0.7416
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5287 - accuracy: 0.7424
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5279 - accuracy: 0.7422
Epoch 78/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5281 - accuracy: 0.7423
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5287 - accuracy: 0.7424
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5282 - accuracy: 0.7426
Epoch 81/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5282 - accuracy: 0.7427
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5280 - accuracy: 0.7429
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5278 - accuracy: 0.7411
Epoch 84/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5284 - accuracy: 0.7423
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5279 - accuracy: 0.7418
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5278 - accuracy: 0.7433
Epoch 87/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5278 - accuracy: 0.7427
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5282 - accuracy: 0.7430
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5282 - accuracy: 0.7427
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5281 - accuracy: 0.7421
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5275 - accuracy: 0.7423
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5275 - accuracy: 0.7426
Epoch 93/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5277 - accuracy: 0.7423
Epoch 94/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5276 - accuracy: 0.7417
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5281 - accuracy: 0.7424
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5274 - accuracy: 0.7422
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5274 - accuracy: 0.7412
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5274 - accuracy: 0.7422
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5273 - accuracy: 0.7418
Epoch 100/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5278 - accuracy: 0.7424

In [31]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5638 - accuracy: 0.7257 - 533ms/epoch - 2ms/step
Loss: 0.5638396739959717, Accuracy: 0.7257142663002014

In [32]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(